### ISSUE TITLE
tls_verify = false in exmple config

### ISSUE THREAD

**Issue by chickahoona** [mawalu/hetzner-gitlab-runner#2]
Usually tls_verify = false is quite a bad thing to do. Providing this "insecure" parameter in a default example config ... questionable at best and causing insecure installations for most people.

Could you explain which communication is usually protected with this TLS check / parameter?

**Comment by mawalu** [comment]
This part of the config is, like most parts of it, directly taken form the [gitlab docs](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html). `tls_verify` defines if the local [docker socket should use TLS](https://docs.docker.com/engine/security/https/), `false` is the default value that gitlab and I think also docker ship with. This isn't a big problem since the default configuration only opens this socket locally and limits access to it to root and the docker group.
